### ISSUE TITLE
Pause/resume for the read test

### ISSUE THREAD

**Issue by birdie-github** [whdd/whdd#15]
Currently you can only terminate it which is very inconvenient.

**Comment by dreamcat4** [comment]
+1 For this feature. Some way to save the read position. And then come back to it later on during another seperate session / invokation of the tool.

**Comment by SilverPuppy** [comment]
You can save the read position: since it shows the operating LBA to you the entire time it is operating, simply write down where it stopped and then enter it when starting the tool later.

**Comment by birdie-github** [comment]
> You can save the read position: since it shows the operating LBA to you the entire time it is operating, simply write down where it stopped and then enter it when starting the tool later.

This requires writing data down and entering it later which is error prone and complicated. I mean how difficult is to implement this feature? Scanning for the space key and pausing/resuming?

**Comment by dreamcat4** [comment]
Indeed. Having the software remember the last saved position is very important for many disks in an array. Because there are many disks to keep track of how far the test has progressed for each one. With very similar serial number to the next disk. On larger capacities it takes many more hours to check the full disk. At any point in time which the scan may be interrupted. Either for performing a software update / reboot. Or otherwise the disk may be required again for real workloads. Until the next operating window ends and the system becomes back to idle again. Then the partial scan can resume and be continued until the start of the next operating window.

If this piece of software is too stupid to keep track itself, then it would alternatively be useful to provide some simple input / output mechanism that can then be scripted. For example with cmdlind flags to specify the resume position and the operation type. flag for the end position. And to split out as text file the last written location and what the operations was, on which disk. None of this stuff should be too terribly difficult to do in a C program. Its more of a case deciding what the interface should be like, which specific features or format. For the way the author of the software here wants for how it should operate.

**Comment by kamilion** [comment]
"I mean how difficult is it to implement this feature?"

Well, for one, you need to have local storage available, or a network share mounted, neither of which are available on my Ubuntu ISOs with whdd included (And default booting TORAM=Yes)

You can already invoke whdd with a python script -- it's worked since 2016.

**Comment by andrey-utkin** [comment]
Interesting idea and discussion.
Not on my plan. Patches welcome. For now please use the workaround by @SilverPuppy :

> You can save the read position: since it shows the operating LBA to you the entire time it is operating, simply write down where it stopped and then enter it when starting the tool later.
